services:
  - type: web
    name: tattoo-studio-bot-python
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8272782280:AAGFCLqzJtQDhhpKxNxWJLR9fh1KWgnHBQg
